apiVersion: v1
kind: Pod
metadata:
  name: mi-app-pod
  namespace: mi-proyecto
spec:
  containers:
  - name: mi-app
    image: python:3.9-alpine
    command: 
    - /bin/sh
    args:
    - -c
    - |
      pip install flask launchdarkly-server-sdk requests
      python -c "
      import os
      import ldclient
      from ldclient.config import Config
      from ldclient import Context
      from flask import Flask, jsonify

      app = Flask(__name__)

      sdk_key = os.environ.get('LAUNCHDARKLY_SDK_KEY', '')
      if sdk_key:
          ldclient.set_config(Config(sdk_key))
          client = ldclient.get()
          print('✅ LaunchDarkly inicializado')
      else:
          client = None
          print('⚠️ LaunchDarkly no configurado')

      def get_feature_flag(user_key, feature_flag_key, default=False):
          if client:
              context = Context.builder(user_key).kind('user').build()
              return client.variation(feature_flag_key, context, default)
          return default

      @app.route('/')
      def home():
          return jsonify({'mensaje': 'API con LaunchDarkly funcionando!'})

      @app.route('/feature-flags')
      def feature_flags():
          flags = {
              'feature_flags': {
                  'nuevo-mensaje-bienvenida': get_feature_flag('test', 'nuevo-mensaje-bienvenida', False),
                  'status-detallado': get_feature_flag('test', 'status-detallado', False)
              }
          }
          return jsonify(flags)

      app.run(host='0.0.0.0', port=5000)
      "
    env:
    - name: LAUNCHDARKLY_SDK_KEY
      value: "sdk-1fb5c5df-e2f9-46ef-9fe4-9225ac56f9d4"
    ports:
    - containerPort: 5000
