version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.12
    environment:
      PYTHONUNBUFFERED: 1

    steps:
      - checkout

      - run:
          name: Verificar instalación de Python
          command: |
            python --version
            pip --version

      - run:
          name: Crear entorno virtual e instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Ejecutar pruebas y cobertura
          command: |
            . venv/bin/activate
            pytest --maxfail=1 --disable-warnings --cov=app --cov-report=xml --html=pytest_report.html --self-contained-html

      - run:
          name: Analizar calidad del código
          command: |
            . venv/bin/activate
            flake8 app --format=html --htmldir=flake-report || true
            pylint app > pylint-report.txt || true

      - run:
          name: Escanear seguridad
          command: |
            . venv/bin/activate
            bandit -r app -f txt -o bandit-report.txt || true

      - store_artifacts:
          path: .
          destination: build_reports

      #  Notificación de éxito
      - run:
          name: Enviar notificación por correo (éxito)
          when: on_success
          command: |
            echo "Pipeline completado exitosamente. Enviando notificación..."
            sudo apt-get update && sudo apt-get install -y msmtp-mta

            printf "account default\nhost smtp.gmail.com\nport 587\nfrom ${GMAIL_USER}\nauth on\nuser ${GMAIL_USER}\npassword ${GMAIL_PASS}\ntls on\ntls_starttls on\n" > ~/.msmtprc
            chmod 600 ~/.msmtprc

            printf "Subject: Pipeline exitoso - ${CIRCLE_JOB} #${CIRCLE_BUILD_NUM}\nFrom: ${GMAIL_USER}\nTo: ${EMAIL_TO}\n\nHola,\n\nEl pipeline '${CIRCLE_PROJECT_REPONAME}' ha finalizado correctamente.\n\nVer detalles en: ${CIRCLE_BUILD_URL}\n\nAtentamente,\nCircleCI\n" | msmtp ${EMAIL_TO}

      #  Notificación de fallo
      - run:
          name: Enviar notificación por correo (fallo)
          when: on_fail
          command: |
            echo "Pipeline falló. Enviando notificación de error..."
            sudo apt-get update && sudo apt-get install -y msmtp-mta

            printf "account default\nhost smtp.gmail.com\nport 587\nfrom ${GMAIL_USER}\nauth on\nuser ${GMAIL_USER}\npassword ${GMAIL_PASS}\ntls on\ntls_starttls on\n" > ~/.msmtprc
            chmod 600 ~/.msmtprc

            printf "Subject:  Error en pipeline - ${CIRCLE_JOB} #${CIRCLE_BUILD_NUM}\nFrom: ${GMAIL_USER}\nTo: ${EMAIL_TO}\n\nHola,\n\nEl pipeline '${CIRCLE_PROJECT_REPONAME}' ha fallado.\n\nRevisa los reportes y logs en: ${CIRCLE_BUILD_URL}\n\nAtentamente,\nCircleCI\n" | msmtp ${EMAIL_TO}

workflows:
  version: 2
  build_test_and_notify:
    jobs:
      - build_and_test
